[package]
name = "rc3d-scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rc3d-core = { workspace = true }
rc3d-fields = { workspace = true }
bytemuck = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slotmap = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

