[package]
name = "rc3d-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rc3d-core = { workspace = true }
rc3d-fields = { workspace = true }
rc3d-scene = { workspace = true }
rc3d-actions = { workspace = true }
serde_json = { workspace = true }
rc3d-render = { workspace = true }
rc3d-engine-api = { workspace = true }
rc3d-gizmo = { workspace = true }
rc3d-pdf = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
egui = "0.36"
egui-wgpu = "0.36"
egui-winit = "0.36"
egui-snarl = { git = "https://github.com/zakarumych/egui-snarl.git", branch = "main" }
eframe = { version = "0.36", default-features = false, features = ["wgpu"] }
egui_ltreeview = "0.9"
rfd = "0.17"
log = { workspace = true }
image = { workspace = true }
egui_extras = { version = "0.36", features = ["all_loaders", "datepicker"] }
egui_commonmark = "0.25"
slotmap = { workspace = true }

[dev-dependencies]
