[package]
name = "rc3d-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rc3d-mesh = { workspace = true }
rc3d-core = { workspace = true }
rc3d-fields = { workspace = true }
rc3d-scene = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
slotmap = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
winit = { workspace = true }
glyphon = { workspace = true }
bitflags = "2"
twox-hash = "1.6.3"
rayon = { workspace = true }
image = { workspace = true }
half = "2"
tracy-client = { workspace = true, optional = true, features = ["enable"] }

[features]
profiler = ["dep:tracy-client"]
