[package]
name = "rc3d-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rc3d-core = { workspace = true }
rc3d-scene = { workspace = true }
rc3d-nurbs = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
gltf = { version = "1", default-features = false, features = ["import", "KHR_lights_punctual", "names", "utils"] }
base64 = "0.22"
image = { workspace = true }
fbxcel = { version = "0.9", features = ["writer"] }
earcutr = "0.4"
spade = "2"
slotmap = "1"

