//! Entity type classification for schema-aware dispatch.
//! Replaces string-based entity name matching with typed dispatch.

/// Known STEP entity types for typed dispatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityType {
    // Curves
    Line,
    Circle,
    Ellipse,
    Polyline,
    BSplineCurve,
    BSplineCurveWithKnots,
    RationalBSplineCurve,
    // Surfaces
    Plane,
    CylindricalSurface,
    ConicalSurface,
    SphericalSurface,
    ToroidalSurface,
    BSplineSurface,
    BSplineSurfaceWithKnots,
    SurfaceOfLinearExtrusion,
    SurfaceOfRevolution,
    OffsetSurface,
    BoundedSurface,
    // Topology
    ClosedShell,
    OpenShell,
    Shell,
    OrientedClosedShell,
    OrientedOpenShell,
    FaceSurface,
    AdvancedFace,
    FaceOuterBound,
    FaceBound,
    EdgeCurve,
    OrientedEdge,
    EdgeLoop,
    PolyLoop,
    VertexPoint,
    CartesianPoint,
    Direction,
    Vector,
    Axis2Placement3D,
    Axis2Placement2D,
    // Assembly
    NextAssemblyUsageOccurrence,
    ProductDefinitionShape,
    ShapeDefinitionRepresentation,
    ShapeRepresentation,
    AdvancedBrepShapeRepresentation,
    ItemDefinedTransformation,
    ManifoldSolidBrep,
    BrepWithVoids,
    ShellBasedSurfaceModel,
    // Product structure
    Product,
    ProductDefinition,
    ProductDefinitionFormation,
    // PMI
    StyledItem,
    PresentationStyleAssignment,
    AnnotationOccurrence,
    DimensionalSize,
    DimensionalCharacteristicRepresentation,
    AngularSize,
    Datum,
    DatumFeature,
    DatumTarget,
    GeometricTolerance,
    // Style / colour
    SurfaceStyleUsage,
    SurfaceSideStyle,
    SurfaceStyleFillArea,
    FillAreaStyle,
    ColourRgb,
    Colour,
    // Meta (supertype wrappers, rarely used directly)
    RepresentationItem,
    GeometricRepresentationItem,
    Curve,
    Surface,
    BoundedCurve,
    // Fallback
    Unknown,
}

impl EntityType {
    /// Resolve entity type from the entity's stored name string.
    pub fn from_name(name: &str) -> Self {
        match name {
            "LINE" => Self::Line,
            "CIRCLE" => Self::Circle,
            "ELLIPSE" => Self::Ellipse,
            "POLYLINE" => Self::Polyline,
            "B_SPLINE_CURVE" => Self::BSplineCurve,
            "B_SPLINE_CURVE_WITH_KNOTS" => Self::BSplineCurveWithKnots,
            "RATIONAL_B_SPLINE_CURVE" => Self::RationalBSplineCurve,
            "PLANE" => Self::Plane,
            "CYLINDRICAL_SURFACE" => Self::CylindricalSurface,
            "CONICAL_SURFACE" => Self::ConicalSurface,
            "SPHERICAL_SURFACE" => Self::SphericalSurface,
            "TOROIDAL_SURFACE" => Self::ToroidalSurface,
            "B_SPLINE_SURFACE" => Self::BSplineSurface,
            "B_SPLINE_SURFACE_WITH_KNOTS" => Self::BSplineSurfaceWithKnots,
            "SURFACE_OF_LINEAR_EXTRUSION" => Self::SurfaceOfLinearExtrusion,
            "SURFACE_OF_REVOLUTION" => Self::SurfaceOfRevolution,
            "OFFSET_SURFACE" => Self::OffsetSurface,
            "BOUNDED_SURFACE" => Self::BoundedSurface,
            "CLOSED_SHELL" => Self::ClosedShell,
            "OPEN_SHELL" => Self::OpenShell,
            "SHELL" => Self::Shell,
            "ORIENTED_CLOSED_SHELL" => Self::OrientedClosedShell,
            "ORIENTED_OPEN_SHELL" => Self::OrientedOpenShell,
            "FACE" | "FACE_SURFACE" => Self::FaceSurface,
            "ADVANCED_FACE" => Self::AdvancedFace,
            "FACE_OUTER_BOUND" => Self::FaceOuterBound,
            "FACE_BOUND" => Self::FaceBound,
            "EDGE_CURVE" => Self::EdgeCurve,
            "ORIENTED_EDGE" => Self::OrientedEdge,
            "EDGE_LOOP" => Self::EdgeLoop,
            "POLY_LOOP" => Self::PolyLoop,
            "VERTEX_POINT" => Self::VertexPoint,
            "CARTESIAN_POINT" => Self::CartesianPoint,
            "DIRECTION" => Self::Direction,
            "VECTOR" => Self::Vector,
            "AXIS2_PLACEMENT_3D" => Self::Axis2Placement3D,
            "AXIS2_PLACEMENT_2D" => Self::Axis2Placement2D,
            "NEXT_ASSEMBLY_USAGE_OCCURRENCE" => Self::NextAssemblyUsageOccurrence,
            "PRODUCT_DEFINITION_SHAPE" => Self::ProductDefinitionShape,
            "SHAPE_DEFINITION_REPRESENTATION" => Self::ShapeDefinitionRepresentation,
            "SHAPE_REPRESENTATION" | "SHAPE_REPRESENTATION_RELATIONSHIP" => Self::ShapeRepresentation,
            "ADVANCED_BREP_SHAPE_REPRESENTATION" => Self::AdvancedBrepShapeRepresentation,
            "ITEM_DEFINED_TRANSFORMATION" => Self::ItemDefinedTransformation,
            "MANIFOLD_SOLID_BREP" => Self::ManifoldSolidBrep,
            "BREP_WITH_VOIDS" => Self::BrepWithVoids,
            "SHELL_BASED_SURFACE_MODEL" => Self::ShellBasedSurfaceModel,
            "PRODUCT" => Self::Product,
            "PRODUCT_DEFINITION" => Self::ProductDefinition,
            "PRODUCT_DEFINITION_FORMATION" | "PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE" => Self::ProductDefinitionFormation,
            "STYLED_ITEM" => Self::StyledItem,
            "PRESENTATION_STYLE_ASSIGNMENT" => Self::PresentationStyleAssignment,
            "ANNOTATION_OCCURRENCE" => Self::AnnotationOccurrence,
            "DIMENSIONAL_SIZE" => Self::DimensionalSize,
            "DIMENSIONAL_CHARACTERISTIC_REPRESENTATION" => Self::DimensionalCharacteristicRepresentation,
            "ANGULAR_SIZE" => Self::AngularSize,
            "DATUM" => Self::Datum,
            "DATUM_FEATURE" => Self::DatumFeature,
            "DATUM_TARGET" => Self::DatumTarget,
            "GEOMETRIC_TOLERANCE" => Self::GeometricTolerance,
            // Style / colour
            "SURFACE_STYLE_USAGE" => Self::SurfaceStyleUsage,
            "SURFACE_SIDE_STYLE" => Self::SurfaceSideStyle,
            "SURFACE_STYLE_FILL_AREA" => Self::SurfaceStyleFillArea,
            "FILL_AREA_STYLE" => Self::FillAreaStyle,
            "COLOUR_RGB" => Self::ColourRgb,
            "COLOUR" => Self::Colour,
            _ => Self::Unknown,
        }
    }
}
