[package]
name = "rc3d-studio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rc3d-studio"
path = "src/main.rs"

[dependencies]
rc3d-core = { workspace = true }
rc3d-scene = { workspace = true }
rc3d-editor = { workspace = true }
rc3d-engine-api = { workspace = true }
rc3d-gizmo = { workspace = true }
rc3d-render = { workspace = true }
rc3d-actions = { workspace = true }
winit = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
wgpu = { workspace = true }
serde_json = { workspace = true }
